name: ci
on:
  push:
  pull_request:
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f templates/requirements.txt ]; then pip install -r templates/requirements.txt; fi
          pip install pytest ruff black
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Test
        run: pytest -q
